
networks:
  spire-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.1

services:
  spire1:
    image: spire-img
    container_name: spire1
    networks:
      spire-net:
        ipv4_address: 192.168.101.101
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pregenerated_keys:/app/spire/pregenerated_keys
      - ./prime/bin/tpm_keys:/app/spire/prime/bin/tpm_keys
    tty: true
    stdin_open: true

  spire2:
    image: spire-img
    container_name: spire2
    networks:
      spire-net:
        ipv4_address: 192.168.101.102
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pregenerated_keys:/app/spire/pregenerated_keys
      - ./prime/bin/tpm_keys:/app/spire/prime/bin/tpm_keys
    tty: true
    stdin_open: true

  spire3:
    image: spire-img
    container_name: spire3
    networks:
      spire-net:
        ipv4_address: 192.168.101.103
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pregenerated_keys:/app/spire/pregenerated_keys
      - ./prime/bin/tpm_keys:/app/spire/prime/bin/tpm_keys
    tty: true
    stdin_open: true

  spire4:
    image: spire-img
    container_name: spire4
    networks:
      spire-net:
        ipv4_address: 192.168.101.104
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pregenerated_keys:/app/spire/pregenerated_keys
      - ./prime/bin/tpm_keys:/app/spire/prime/bin/tpm_keys
    tty: true
    stdin_open: true


  spire5:
    image: spire-img
    container_name: spire5
    networks:
      spire-net:
        ipv4_address: 192.168.101.107
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pregenerated_keys:/app/spire/pregenerated_keys
      - ./prime/bin/tpm_keys:/app/spire/prime/bin/tpm_keys
    tty: true
    stdin_open: true

    
  spire6:
    image: spire-img
    container_name: spire6
    networks:
      spire-net:
        ipv4_address: 192.168.101.108
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pregenerated_keys:/app/spire/pregenerated_keys
      - ./prime/bin/tpm_keys:/app/spire/prime/bin/tpm_keys
    tty: true
    stdin_open: true