version: '3.9'

networks:
  spire-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.1

services:
  conf-agent:
    image: spire-img
    container_name: conf-agent
    networks:
      spire-net:
        ipv4_address: 192.168.101.201
    cap_add:
      - NET_ADMIN
    environment:
      - SPIRE_MODE=conf_agent

  conf-manager:
    image: spire-img
    container_name: conf-manager
    networks:
      spire-net:
        ipv4_address: 192.168.101.202
    cap_add:
      - NET_ADMIN
    environment:
      - SPIRE_MODE=conf_manager
    tty: true
    stdin_open: true
